name: edit_srt_for_youtube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  deep_pick: ^1.1.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  path: ^1.9.1
  youtube_explode_dart: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
